name: serial_flutterblue
description: A serial flutterblue based on https://github.com/itavero/flutter-ble-uart/
version: 0.0.1
author: y60yu1ii
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: 0.7.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter