name: serial_flutterblue
description: A serial flutterblue based on https://github.com/itavero/flutter-ble-uart/
version: 0.0.4
author: y60yu1ii

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ble_lib: ^2.3.1
  permission_handler: ^5.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter